### PR TITLE
Update versions CDH513

### PR DESCRIPTION
**Pull request by swetharaj**

### CODE REVIEW

**Comment by jdcba** [comment]
Hi @swetharaj I just noticed this is using the old ‘ci’ repo which is deprecated and was in fact removed from github.com for a while. I don’t think we ever got this to work. For example with spectroscopy we were successful only after migrating it to ci2: https://github.com/CommBank/spectroscopy/commit/c5cb74c60b41880c4353bc9bc3f93d6176c43386

**Comment by swetharaj** [comment]
@jdcba ...thanks for noticing.. I had actually changed it on Friday, but somehow got overwritten in one of the commits.

**Comment by jdcba** [comment]
Thanks for fixing the build! The whitespace is a bit weird but I guess that was autoformatting.

**Comment by jdcba** [comment]
I also recommend updating the Copyright notices in the modified files (2014-2018). Well, we have done that with other repos.

**Comment by swetharaj** [comment]
> I also recommend updating the Copyright notices in the modified files (2014-2018). Well, we have done that with other repos.

sure.. can do that

**Pull request merged**
